### ISSUE TITLE
Grace Period for Existing Tokens

### ISSUE THREAD

**Issue by MTaylor5152** [CommissionerPeirce/SafeHarbor2.0#34]
These regulations will create a favorable environment for new tokens in the early stages of development. However, the developers and holders of existing tokens that do not wish to be regulated as securities need to have time to implement changes to their networks in order to operate within the preferred regulatory environment. 

If a grace period is not provided for the developers to implement changes it will start a panic with many exchanges, development teams and token holders which will destroy large amounts of wealth. Legacy software systems often require more time to change than new systems. A three-year period to make changes would be necessary if SafeHarbor2.0 were to become law in some form.

**Comment by earjuice** [comment]
Tell Ken we arent leaving....
